<a href="https://colab.research.google.com/github/arpitguptaalm1-art/DSV-Lab/blob/main/day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv("/content/Animals.csv")

In [ ]:
print(df)

            rownames       body   brain
0    Mountain beaver      1.350     8.1
1                Cow    465.000   423.0
2          Grey wolf     36.330   119.5
3               Goat     27.660   115.0
4         Guinea pig      1.040     5.5
5        Dipliodocus  11700.000    50.0
6     Asian elephant   2547.000  4603.0
7             Donkey    187.100   419.0
8              Horse    521.000   655.0
9       Potar monkey     10.000   115.0
10               Cat      3.300    25.6
11           Giraffe    529.000   680.0
12           Gorilla    207.000   406.0
13             Human     62.000  1320.0
14  African elephant   6654.000  5712.0
15       Triceratops   9400.000    70.0
16     Rhesus monkey      6.800   179.0
17          Kangaroo     35.000    56.0
18    Golden hamster      0.120     1.0
19             Mouse      0.023     0.4
20            Rabbit      2.500    12.1
21             Sheep     55.500   175.0
22            Jaguar    100.000   157.0
23        Chimpanzee     52.160   440.0
24               Rat      0.280     1.9
25     Brachiosaurus  87000.000   154.5
26              Mole      0.122     3.0
27               Pig    192.000   180.0

In [ ]:
df.head()

          rownames    body  brain
0  Mountain beaver    1.35    8.1
1              Cow  465.00  423.0
2        Grey wolf   36.33  119.5
3             Goat   27.66  115.0
4       Guinea pig    1.04    5.5

In [ ]:
df.tail()

         rownames       body  brain
23     Chimpanzee     52.160  440.0
24            Rat      0.280    1.9
25  Brachiosaurus  87000.000  154.5
26           Mole      0.122    3.0
27            Pig    192.000  180.0

In [ ]:
df.shape

(28, 3)

In [ ]:
df.describe()

               body        brain
count     28.000000    28.000000
mean    4278.438750   574.521429
std    16480.490379  1334.929191
min        0.023000     0.400000
25%        3.100000    22.225000
50%       53.830000   137.000000
75%      479.000000   420.000000
max    87000.000000  5712.000000

In [ ]:
df.columns

Index(['rownames', 'body', 'brain'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   rownames  28 non-null     object
 1   body      28 non-null     float64
 2   brain     28 non-null     float64
dtypes: float64(2), object(1)
memory usage: 804.0+ bytes

In [ ]:
df.isnull().sum()

rownames    0
body        0
brain       0
dtype: int64